name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          API_HOST: ${{ secrets.METADOXIL_API_HOST }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          
