name: Gatsby Publish

on:
  push:
    branches:
      - main
  repository_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "API_HOST=${{ secrets.METADOXIL_API_HOST }}" >> .env
      
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Install npm dependencies
        run: npm install
        
      - name: Run build task
        run: npm run build --prefix-paths
        
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          host='${{ secrets.SSH_HOST }}'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
          
      - name: Deploy with rsync
        run: rsync -avz --delete --exclude 'cgi-bin' public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_TARGET_FOLDER }}  | grep failed
