name: Gatsby Publish

on:
  push:
    branches:
      - main
  repository_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "API_HOST=${{ secrets.METADOXIL_API_HOST }}" >> .env
      
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: public
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -rav --delete public/index.html ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_TARGET_FOLDER }}
