name: Gatsby Publish

on:
  push:
    branches:
      - main
  repository_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "API_HOST=${{ secrets.METADOXIL_API_HOST }}" >> .env
      
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ~/src
      - name: Display structure of downloaded files
        run: ls -R
